stages:
  data_preprocessing:
    cmd: python src/s1_data_preprocessing.py
    deps:
      - src/s1_data_preprocessing.py
      - artifacts/dataset.csv
    outs:
      - artifacts/Preprocessed

  data_transformation:
    cmd: python src/s2_data_transformation.py
    deps:
      - src/s2_data_transformation.py
      - src/s1_data_preprocessing.py
      - artifacts/Preprocessed
    outs:
      - artifacts/Train
      - artifacts/Test

  model_training:
    cmd: python src/s3_model_training.py
    deps:
      - src/s3_model_training.py
      - src/s2_data_transformation.py
      - artifacts/Train
    outs:
      - artifacts/Model
      - artifacts/Metrics/train_metrics.json

  model_evaluation:
    cmd: python src/s4_model_evaluation.py
    deps:
      - src/s4_model_evaluation.py
      - src/s2_data_transformation.py
      - artifacts/Test
      - artifacts/Model
    outs:
      - artifacts/Metrics/eval_metrics.json

  app:
    cmd: python app.py
    deps:
      - app.py
      - artifacts/Model
